name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    outputs:
      segments: ${{ steps.get-segments.outputs.segments }}
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files for download
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Run download script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SW5wbGJtRnJkVEEzSWl3aVVrVlFUeUk2SWxwcGJtbHRZWEoxSWl3aVZFZGZRVkJKWDBsRUlqb2lNVFkxTkRZeU56QWlMQ0pVUjE5QlVFbGZTRUZUU0NJNklqRmxNV1ZtTVdKaVlqWmxPR00yWW1NNU1EQXlNRGRqWVRWaE1URmpaalppSWl3aVZFZGZRazlVWDFSUFMwVk9Jam9pTnpJeU9ETTJOREU1TWpwQlFVVjBOakZtUm14U2FYbFFja1JNT1c1aVZYWjBYekJUTmxOdFZXTXhOVUpHVlNJc0lrWkpURVVpT2pFME5URXNJa1pKVEVWZlRrRk5SU0k2SWx0VE1ESXRNakJkSUZSb1pTQkJjRzkwYUdWallYSjVJRVJwWVhKcFpYTWdXelE0TUhCZElGdFRkV0pkSUVCQmJtbHRaWE5mVDJObFlXNHViV3QySWl3aVNVUWlPaUpVYUdWZk1HWTRNR0k5TVRROU5EZ3djQ0lzSWtOTlJDSTZJbHB0V25SalIxWnVTVU14Y0VsSWRIQmliRGx0WVZkNGJHWlRRWFJhYld4elpFZFdlVmd5VG5aaVdFSnpXbGhuWjBsdFVubFpXR1F3V2xob01GQlhXblppYmxKdFlWZDRiRkJYWjNWa1NGSnRUMjVTYkdWSVVUbEtlVUpDWW0xc2RGcFlUV2RVTWs1c1dWYzBaMHA2Y0cxaU1qVXdXVEk1YzJJelNUbGtNbWh3WkVkVk5scHRPWFZrU0U1d1pXMVZPVTFxVVRabFJEQjRUVVJ3TlZCVVJYZFBiVloxV1ZkS2MxcFVNRzVaYlZZd1pESldiR0pwYURCTVJFRnpUbFJCZDB0VFl6WlpWM2gzWVVkRk9Vb3liRzFMUjNnd1MwaFJjMDVFYXpWTFUzZDRURWRzYlV0SGVEQkxTRkZ6VGxSQmQwdFRkMjlOVXpCdlpFTXdNRTlVYTNCTFV6aDRURVJCY0V0VFNXZE1WekZvWTBOQmQwbERNWFJhV0ZKb1drZEdNRmxVY0hwUGJVVm5aRWRzTUdKSFZUbEphMEpDWW0xc2RGcFlUbVpVTWs1c1dWYzBhVWxETVhSYVdGSm9Xa2RHTUZsVWNIcFBiazFuWkVkc01HSkhWVGxKYTBKQ1ltMXNkRnBZVG1aVU1rNXNXVmMwYVVsRE1YUmFXRkpvV2tkR01GbFRRakJoV0ZKeldsUXdhVkZGUm5WaFZ6RnNZekU1VUZreVZtaGlhVWxuVEZkTk5tUnBRbk5oVjBwNlpHNVNhR1JxUldkTVdFSjVXbGhPYkdSRFFUSkpRekZ1U1VSSk1FMURRWFJqZVVFMFRsUlNORTVFWjNkSlF6RjNZVmhvWmxwdE1UQkpTR3d4WkdwUmVVMUlRV2RNV0U0eVpFZEdNazFUTVhkWldFcG9ZbGhOWjJSSVZuVmFWREI0VDIxYWNHSkhNSFJhTTBwb1lWYzBPVTFEUVhSWk0wcHRTVVJWZDBsRE1YTmlNbVJ6V2xoYWJHSkRRbXhqYmtwMlkybEJkRmw2Y0doSlIzaHdXVzA1ZDJSWVRXZE1WMFpxU1VSSloweFhSbWxKUkZGM1lYbEJkRmw2Y0hwSlIwNTJZMGhyWjJVeU9YZFlNbHB3WWtkV09VbERNVFVpTENKVVNGVk5RazVCU1V3aU9pSXlNamdpTENKQlZWUklUMUlpT2lJeE1qYzBNRE00TXpBd0luMD0=
      - name: Get segments
        id: get-segments
        run: |
          SEGMENTS=$(jq -c '.OUTPUT_FILES | keys' /app/data.json)
          echo "segments=$SEGMENTS" >> $GITHUB_OUTPUT
  encode:
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        segment: ${{ fromJson(needs.download.outputs.segments) }}
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Encode segment
        run: |
          cd /app
          mkdir -p encoded
          python3 encode.py ${{ matrix.segment }}
      - name: Save encoded segment
        uses: actions/upload-artifact@v4
        with:
          name: segment-${{ matrix.segment }}
          path: /app/encoded
  upload:
    needs: encode
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Download all encoded segments
        uses: actions/download-artifact@v4
        with:
          pattern: segment-*
          path: /app/encoded
      - name: Extract necessary files and clean up
        run: |
          cd /app/encoded

          for dir in segment-*; do
            if [ -d "$dir" ]; then
              mv "$dir"/* .
              rmdir "$dir"
            fi
          done

          ls -sh
      - name: Merge and upload files
        run: |
          cd /app

          python3 upload.py
  delete:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: segment-*
