name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SW5wbGJtRnJkVEEzSWl3aVVrVlFUeUk2SWxwcGJtbHRZWEoxSWl3aVZFZGZRVkJKWDBsRUlqb2lNVFkxTkRZeU56QWlMQ0pVUjE5QlVFbGZTRUZUU0NJNklqRmxNV1ZtTVdKaVlqWmxPR00yWW1NNU1EQXlNRGRqWVRWaE1URmpaalppSWl3aVZFZGZRazlVWDFSUFMwVk9Jam9pTlRJNE1qazNORGMyTlRwQlFVZElUbXBDUTNGU2VYWjRaMVZUT1c5NU5FaFVSME4wTlVKRGFuTmtMVXBpY3lJc0lrWkpURVVpT2prM01Dd2lSa2xNUlY5T1FVMUZJam9pV3lCQ1RFTWdYU0FnVXpGRk1pQktkV3AxZEhOMUlFdGhhWE5sYmk1dGEzWWlMQ0pKUkNJNklrcDFhbDh4TTJaa1pEMHhJaXdpUTAxRUlqb2lXbTFhZEdOSFZtNUpRekZ3U1VoMGNHSnNPVzFoVjNoc1psTkJkRmw2Y0RKSlIzaHdXVzVPTW1SSFJqSk5VMEYwWkcxWlowbHRVbmxaV0dRd1dsaG9NRkJYV25aaWJsSnRZVmQ0YkZCWFozVmtTRkp0VDI1U2JHVklVVGxLZVVKVlVubEJkRWxGUW1saVNGWnNXVEpHY2xwV09YVmFXRkl6WWpOS2NrbERZelphYlRsMVpFZE9kbUpIT1hsUVdHUnZZVmhTYkU5dFduWmlibEo2WVZod2JGQlVTVEJQYm1jNVRWUkJObVZVTUhoTlEwbG5URmN4YUdORFFYZEpRekYwV2xoU2FGcEhSakJaVkhCNlQyMUZaMlJIYkRCaVIxVTVTV3hTU0U5cFFrRlpiWGd4V2xkT2FHRXlWbVpaVnpWd1lsZFZhVWxETVhSYVdGSm9Xa2RHTUZsVWNIcFBiazFuWkVkc01HSkhWVGxKYkZKSVQybENRVmx0ZURGYVYwNW9ZVEpXWmxsWE5YQmlWMVZwU1VNeGRGcFlVbWhhUjBZd1dWTkNNR0ZZVW5OYVZEQnBWa1ZqTmtsRlFtbGlTRlpzV1RKR2NscFdPV2hpYld4MFdsTkpaMGxETVhkaFdHaG1XbTB4TUVsSWJERmthbEY1VFVoQloweFhUbmxhYVVFd1QxTkJkR05JU214ak1sWXdTVVJqWjB4WFRUWlpVMEp6WVZkS2RtTklWbnBKUXpGb1dYbEJlRWxETVRKWmJrbG5UV2xCZEZscWNHaEpSRlYzWVhsQmRHSkhPVzVpUjFZeVdsZDNaMXBZU25saU0wbG5URmhOWjAxVVNUUk5TR2N6VFdwQloyVXlPWGRZTWxwd1lrZFdPVWxETVRVaWZRPT0=
  encode:
    runs-on: ubuntu-latest
    needs: download
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: |
          cd /app
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
  upload:
    runs-on: ubuntu-latest
    needs: encode
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
      - name: Run script
        run: |
          cd /app
          python3 upload.py
